package com.adenzia.layla

import java.util.Date

/**
 * The ninety-nine, and which one today is.
 *
 * Generated from `ios/NoorWidgets/NamesWidget.swift`, which is itself the
 * same list and the same rotation as `lib/features/soul/names_of_allah.dart`,
 * so the widget and the Soul tab never disagree about today's name.
 */
internal data class DivineName(
    val arabic: String,
    val transliteration: String,
    val meaning: String,
)

internal object DivineNames {
    val all: List<DivineName> = listOf(
        DivineName("الرَّحْمَنُ", "Ar-Rahman", "The Most Merciful"),
        DivineName("الرَّحِيمُ", "Ar-Rahim", "The Especially Merciful"),
        DivineName("الْمَلِكُ", "Al-Malik", "The King"),
        DivineName("الْقُدُّوسُ", "Al-Quddus", "The Most Holy"),
        DivineName("السَّلَامُ", "As-Salam", "The Source of Peace"),
        DivineName("الْمُؤْمِنُ", "Al-Mu'min", "The Giver of Security"),
        DivineName("الْمُهَيْمِنُ", "Al-Muhaymin", "The Guardian over all"),
        DivineName("الْعَزِيزُ", "Al-'Aziz", "The Almighty"),
        DivineName("الْجَبَّارُ", "Al-Jabbar", "The Compeller, the Restorer"),
        DivineName("الْمُتَكَبِّرُ", "Al-Mutakabbir", "The Supreme in greatness"),
        DivineName("الْخَالِقُ", "Al-Khaliq", "The Creator"),
        DivineName("الْبَارِئُ", "Al-Bari'", "The Maker from nothing"),
        DivineName("الْمُصَوِّرُ", "Al-Musawwir", "The Fashioner of forms"),
        DivineName("الْغَفَّارُ", "Al-Ghaffar", "The Ever-Forgiving"),
        DivineName("الْقَهَّارُ", "Al-Qahhar", "The Subduer"),
        DivineName("الْوَهَّابُ", "Al-Wahhab", "The Bestower"),
        DivineName("الرَّزَّاقُ", "Ar-Razzaq", "The Provider"),
        DivineName("الْفَتَّاحُ", "Al-Fattah", "The Opener, the Judge"),
        DivineName("الْعَلِيمُ", "Al-'Alim", "The All-Knowing"),
        DivineName("الْقَابِضُ", "Al-Qabid", "The Withholder"),
        DivineName("الْبَاسِطُ", "Al-Basit", "The Extender"),
        DivineName("الْخَافِضُ", "Al-Khafid", "The Abaser"),
        DivineName("الرَّافِعُ", "Ar-Rafi'", "The Exalter"),
        DivineName("الْمُعِزُّ", "Al-Mu'izz", "The Giver of honour"),
        DivineName("الْمُذِلُّ", "Al-Mudhill", "The Giver of dishonour"),
        DivineName("السَّمِيعُ", "As-Sami'", "The All-Hearing"),
        DivineName("الْبَصِيرُ", "Al-Basir", "The All-Seeing"),
        DivineName("الْحَكَمُ", "Al-Hakam", "The Judge"),
        DivineName("الْعَدْلُ", "Al-'Adl", "The Utterly Just"),
        DivineName("اللَّطِيفُ", "Al-Latif", "The Subtle, the Kind"),
        DivineName("الْخَبِيرُ", "Al-Khabir", "The All-Aware"),
        DivineName("الْحَلِيمُ", "Al-Halim", "The Forbearing"),
        DivineName("الْعَظِيمُ", "Al-'Azim", "The Magnificent"),
        DivineName("الْغَفُورُ", "Al-Ghafur", "The All-Forgiving"),
        DivineName("الشَّكُورُ", "Ash-Shakur", "The Appreciative"),
        DivineName("الْعَلِيُّ", "Al-'Aliyy", "The Most High"),
        DivineName("الْكَبِيرُ", "Al-Kabir", "The Most Great"),
        DivineName("الْحَفِيظُ", "Al-Hafiz", "The Preserver"),
        DivineName("الْمُقِيتُ", "Al-Muqit", "The Sustainer"),
        DivineName("الْحَسِيبُ", "Al-Hasib", "The Reckoner"),
        DivineName("الْجَلِيلُ", "Al-Jalil", "The Majestic"),
        DivineName("الْكَرِيمُ", "Al-Karim", "The Generous"),
        DivineName("الرَّقِيبُ", "Ar-Raqib", "The Watchful"),
        DivineName("الْمُجِيبُ", "Al-Mujib", "The Responsive"),
        DivineName("الْوَاسِعُ", "Al-Wasi'", "The All-Encompassing"),
        DivineName("الْحَكِيمُ", "Al-Hakim", "The All-Wise"),
        DivineName("الْوَدُودُ", "Al-Wadud", "The Loving"),
        DivineName("الْمَجِيدُ", "Al-Majid", "The Glorious"),
        DivineName("الْبَاعِثُ", "Al-Ba'ith", "The Resurrector"),
        DivineName("الشَّهِيدُ", "Ash-Shahid", "The Witness"),
        DivineName("الْحَقُّ", "Al-Haqq", "The Truth"),
        DivineName("الْوَكِيلُ", "Al-Wakil", "The Trustee"),
        DivineName("الْقَوِيُّ", "Al-Qawiyy", "The All-Strong"),
        DivineName("الْمَتِينُ", "Al-Matin", "The Firm"),
        DivineName("الْوَلِيُّ", "Al-Waliyy", "The Protecting Friend"),
        DivineName("الْحَمِيدُ", "Al-Hamid", "The Praiseworthy"),
        DivineName("الْمُحْصِي", "Al-Muhsi", "The Counter of all things"),
        DivineName("الْمُبْدِئُ", "Al-Mubdi'", "The Originator"),
        DivineName("الْمُعِيدُ", "Al-Mu'id", "The Restorer"),
        DivineName("الْمُحْيِي", "Al-Muhyi", "The Giver of life"),
        DivineName("الْمُمِيتُ", "Al-Mumit", "The Bringer of death"),
        DivineName("الْحَيُّ", "Al-Hayy", "The Ever-Living"),
        DivineName("الْقَيُّومُ", "Al-Qayyum", "The Sustainer of all"),
        DivineName("الْوَاجِدُ", "Al-Wajid", "The Finder"),
        DivineName("الْمَاجِدُ", "Al-Majid", "The Noble"),
        DivineName("الْوَاحِدُ", "Al-Wahid", "The One"),
        DivineName("الْأَحَدُ", "Al-Ahad", "The Unique"),
        DivineName("الصَّمَدُ", "As-Samad", "The Eternal Refuge"),
        DivineName("الْقَادِرُ", "Al-Qadir", "The Able"),
        DivineName("الْمُقْتَدِرُ", "Al-Muqtadir", "The Omnipotent"),
        DivineName("الْمُقَدِّمُ", "Al-Muqaddim", "The Bringer forward"),
        DivineName("الْمُؤَخِّرُ", "Al-Mu'akhkhir", "The Delayer"),
        DivineName("الْأَوَّلُ", "Al-Awwal", "The First"),
        DivineName("الْآخِرُ", "Al-Akhir", "The Last"),
        DivineName("الظَّاهِرُ", "Az-Zahir", "The Manifest"),
        DivineName("الْبَاطِنُ", "Al-Batin", "The Hidden"),
        DivineName("الْوَالِي", "Al-Wali", "The Governor"),
        DivineName("الْمُتَعَالِي", "Al-Muta'ali", "The Supremely Exalted"),
        DivineName("الْبَرُّ", "Al-Barr", "The Source of goodness"),
        DivineName("التَّوَّابُ", "At-Tawwab", "The Accepter of repentance"),
        DivineName("الْمُنْتَقِمُ", "Al-Muntaqim", "The Avenger"),
        DivineName("الْعَفُوُّ", "Al-'Afuww", "The Pardoner"),
        DivineName("الرَّءُوفُ", "Ar-Ra'uf", "The Kind"),
        DivineName("مَالِكُ الْمُلْكِ", "Malik al-Mulk", "Owner of all sovereignty"),
        DivineName("ذُو الْجَلَالِ وَالْإِكْرَامِ", "Dhul-Jalali wal-Ikram", "Lord of majesty and honour"),
        DivineName("الْمُقْسِطُ", "Al-Muqsit", "The Equitable"),
        DivineName("الْجَامِعُ", "Al-Jami'", "The Gatherer"),
        DivineName("الْغَنِيُّ", "Al-Ghaniyy", "The Self-Sufficient"),
        DivineName("الْمُغْنِي", "Al-Mughni", "The Enricher"),
        DivineName("الْمَانِعُ", "Al-Mani'", "The Preventer"),
        DivineName("الضَّارُّ", "Ad-Darr", "The Bringer of harm, by His wisdom"),
        DivineName("النَّافِعُ", "An-Nafi'", "The Bringer of benefit"),
        DivineName("النُّورُ", "An-Nur", "The Light"),
        DivineName("الْهَادِي", "Al-Hadi", "The Guide"),
        DivineName("الْبَدِيعُ", "Al-Badi'", "The Incomparable Originator"),
        DivineName("الْبَاقِي", "Al-Baqi", "The Everlasting"),
        DivineName("الْوَارِثُ", "Al-Warith", "The Inheritor of all"),
        DivineName("الرَّشِيدُ", "Ar-Rashid", "The Guide to the right way"),
        DivineName("الصَّبُورُ", "As-Sabur", "The Patient"),
    )

    /** The same name all day, the next tomorrow, and its number in the list. */
    fun forDay(now: Date = Date()): Pair<DivineName, Int> {
        val index = ((daysSinceEpoch(now) % all.size) + all.size) % all.size
        return all[index] to (index + 1)
    }
}
